services:
  - type: web
    name: stockly-api
    env: java
    region: frankfurt
    buildCommand: cd Api && ./mvnw clean package -DskipTests
    startCommand: java -Dspring.profiles.active=prod -jar Api/target/Api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.qhvlexqrempqetnwrcxr
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: PORT
        value: 8081